"""mcp_bundled のバンドル。

`bundle.yml` が mcp_bundled の **定義 + ビルド宣言**（instance の index.yml に相当する単一の
ソースファイル）。3 段階:
- `init`:   `bundle.yml` の雛形を生成して初期化する。`--clean` は定義 `bundle.yml` を残して
            ディレクトリを一掃する。
- `bundle`: 定義（subagent / skill / tool）を `<name>/vendor/` へ vendoring し、さらに
            `requirements.txt` / `entrypoint.py` / `Dockerfile` を生成する（docker build コンテキスト）。
- `build`:  既定ランタイム docker のイメージビルドコマンドを生成・表示する（ローカル非汚染）。
"""

from __future__ import annotations

import yaml

from .config import ENTRY_FILES, LAYERS
from .registry import RegistryArray

# mcp_bundled の定義 + ビルド宣言ファイル（= mcp_bundled のエントリファイル）
SPEC_FILE = "bundle.yml"
# vendoring / 生成物の出力先（= docker build コンテキスト）。registry と同じ構造でミラーする。
VENDOR_DIR = "vendor"
# include 未指定時の既定（内包物を上から順に解決する）
DEFAULT_INCLUDE = ["subagent", "skills", "tools"]

# --- 生成テンプレート ----------------------------------------------------------

BUNDLE_YML_TEMPLATE = """\
# bundle.yml — mcp_bundled の定義 + ビルド宣言（juice mcp_bundled init が生成。編集可）
apiVersion: juice/v1
kind: mcp_bundled
name: {name}
namespace: {namespace}

# build で生成する docker イメージ名（タグなし）と version
image: juice/{name}
version: 0.0.1

# 結線（定義）— 編集して埋める
subagent:
skills: []
tools: {{}}

# vendoring 対象（省略時は subagent/skills/tools）
include:
  - subagent
  - skills
  - tools
"""

REQUIREMENTS_TXT = """\
# generated by juice — entrypoint と mcp_server 実行に必要な一般パッケージ
mcp
pyyaml
"""

DOCKERFILE = """\
# generated by juice — `juice mcp_bundled bundle` で再生成（手編集しない）
FROM python:3.12-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
ENTRYPOINT ["python", "entrypoint.py"]
"""

ENTRYPOINT_PY = '''\
"""juice bundle のエントリポイント（自動生成）。

この bundle 自体を 1 つの **mcp_server** として stdio(JSON-RPC) で公開する（actor = mcp_server）。
公開する tool は内部のバック server（ここではモック mock_server.py）へ proxy する。
MCP の簡易版で、標準ライブラリのみで動く。

疎通確認（応答例）:
    echo '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"get_forecast","arguments":{"city":"Tokyo"}}}' | python entrypoint.py
"""

from __future__ import annotations

import json
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).parent
NAME = "__BUNDLE_NAME__"


class StdioClient:
    """stdio 上の JSON-RPC でバック mcp_server に話す最小クライアント。"""

    def __init__(self, command: list[str]) -> None:
        self.proc = subprocess.Popen(
            command, stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True, cwd=str(HERE)
        )
        self._id = 0

    def call(self, method: str, params: dict | None = None) -> dict:
        self._id += 1
        req = {"jsonrpc": "2.0", "id": self._id, "method": method, "params": params or {}}
        self.proc.stdin.write(json.dumps(req, ensure_ascii=False) + "\\n")
        self.proc.stdin.flush()
        return json.loads(self.proc.stdout.readline())

    def close(self) -> None:
        self.proc.stdin.close()
        self.proc.terminate()


def serve() -> None:
    """この bundle を mcp_server として stdin/stdout で公開し、バック server へ proxy する。"""
    backing = StdioClient([sys.executable, str(HERE / "mock_server.py")])
    backing.call("initialize")
    tools = backing.call("tools/list")["result"]["tools"]

    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        req = json.loads(line)
        method = req.get("method")
        try:
            if method == "initialize":
                result = {"serverInfo": {"name": NAME, "version": "0.0.1"}, "capabilities": {"tools": {}}}
            elif method == "tools/list":
                result = {"tools": tools}
            elif method == "tools/call":
                result = backing.call("tools/call", req.get("params") or {})["result"]
            else:
                raise ValueError(f"unknown method: {method}")
            resp = {"jsonrpc": "2.0", "id": req.get("id"), "result": result}
        except Exception as e:  # noqa: BLE001
            resp = {"jsonrpc": "2.0", "id": req.get("id"), "error": {"message": str(e)}}
        sys.stdout.write(json.dumps(resp, ensure_ascii=False) + "\\n")
        sys.stdout.flush()

    backing.close()


if __name__ == "__main__":
    serve()
'''

MOCK_SERVER_PY = '''\
"""モック mcp_server（自動生成）。

stdio 上の JSON-RPC（MCP の簡易版）で initialize / tools/list / tools/call に応答する。
get_forecast(city) はダミー予報を返す。実 server に差し替えるまでの接続確認用。
"""

from __future__ import annotations

import json
import sys

TOOLS = [
    {
        "name": "get_forecast",
        "description": "都市の天気予報を返す（モック）",
        "inputSchema": {
            "type": "object",
            "properties": {"city": {"type": "string"}},
            "required": ["city"],
        },
    }
]


def handle(req: dict) -> dict:
    method = req.get("method")
    if method == "initialize":
        return {"serverInfo": {"name": "mock-weather", "version": "0.0.1"}, "capabilities": {"tools": {}}}
    if method == "tools/list":
        return {"tools": TOOLS}
    if method == "tools/call":
        args = (req.get("params") or {}).get("arguments", {})
        city = args.get("city", "?")
        return {"content": [{"type": "text", "text": f"{city}: 晴れ 26C（モック予報）"}]}
    raise ValueError(f"unknown method: {method}")


def main() -> int:
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        req = json.loads(line)
        try:
            resp = {"jsonrpc": "2.0", "id": req.get("id"), "result": handle(req)}
        except Exception as e:  # noqa: BLE001
            resp = {"jsonrpc": "2.0", "id": req.get("id"), "error": {"message": str(e)}}
        sys.stdout.write(json.dumps(resp, ensure_ascii=False) + "\\n")
        sys.stdout.flush()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

# --- 内部ヘルパ ----------------------------------------------------------------


def _spec(registries: RegistryArray, name: str) -> dict:
    """mcp_bundled の定義（bundle.yml）を dict で読む。"""
    return yaml.safe_load(registries.read("mcp_bundled", name, SPEC_FILE)) or {}


def _deps(spec: dict, include: list[str]) -> list[tuple[str, str]]:
    """定義から (layer, name) の内包物一覧を include 順に返す。"""
    deps: list[tuple[str, str]] = []
    if "subagent" in include and spec.get("subagent"):
        deps.append(("subagent", spec["subagent"]))
    if "skills" in include and spec.get("skills"):
        deps += [("skill", s) for s in spec["skills"]]
    if "tools" in include and spec.get("tools"):
        tools = spec["tools"]
        names = list(tools.keys()) if isinstance(tools, dict) else list(tools)
        deps += [("tool", t) for t in names]
    return deps


def _vendor(registries: RegistryArray, name: str) -> list[str]:
    """`<name>/vendor/` をクリーンしてから内包物を registry と同じ構造でコピーする。"""
    spec = _spec(registries, name)
    include = spec.get("include") or DEFAULT_INCLUDE
    registries.remove("mcp_bundled", name, VENDOR_DIR)  # 旧 vendor を一掃
    vendored: list[str] = []
    for layer, dep in _deps(spec, include):
        raw = registries.read(layer, dep)
        rel = f"{VENDOR_DIR}/{LAYERS[layer]}/{dep}/{ENTRY_FILES[layer]}"
        registries.write("mcp_bundled", name, rel, raw)
        vendored.append(f"mcp_bundled/{name}/{rel}")
    return vendored


# --- コマンド ------------------------------------------------------------------


def init(registries: RegistryArray, name: str, clean: bool = False) -> dict:
    """`bundle.yml` の雛形を生成して初期化する。

    既に初期化済み（bundle.yml が存在）なら `FileExistsError`。`clean=True` の場合は
    パッケージディレクトリを一掃して再初期化する（定義 `bundle.yml` は退避して残す）。
    """
    exists = registries.exists("mcp_bundled", name, SPEC_FILE)
    if not clean and exists:
        raise FileExistsError(
            f"already initialized: mcp_bundled/{name}/{SPEC_FILE} (use --clean to clean & reinitialize)"
        )
    if clean:
        # ディレクトリを丸ごとクリーンアップ。定義 bundle.yml は退避して書き戻す（無ければ雛形）。
        spec_text = registries.read("mcp_bundled", name, SPEC_FILE) if exists else None
        registries.remove("mcp_bundled", name, "")
        if spec_text is None:
            spec_text = BUNDLE_YML_TEMPLATE.format(
                namespace=registries.namespace, name=name
            )
        registries.write("mcp_bundled", name, SPEC_FILE, spec_text)
    else:
        registries.write(
            "mcp_bundled",
            name,
            SPEC_FILE,
            BUNDLE_YML_TEMPLATE.format(namespace=registries.namespace, name=name),
        )
    return {
        "kind": "init",
        "mcp_bundled": name,
        "spec": f"mcp_bundled/{name}/{SPEC_FILE}",
    }


def bundle(registries: RegistryArray, name: str) -> dict:
    """内包物を vendoring し、build コンテキスト（requirements/entrypoint/Dockerfile）を生成する。"""
    vendored = _vendor(registries, name)

    generated = []
    for fname, text in (
        ("requirements.txt", REQUIREMENTS_TXT),
        ("entrypoint.py", ENTRYPOINT_PY.replace("__BUNDLE_NAME__", name)),
        ("mock_server.py", MOCK_SERVER_PY),
        ("Dockerfile", DOCKERFILE),
    ):
        registries.write("mcp_bundled", name, f"{VENDOR_DIR}/{fname}", text)
        generated.append(f"mcp_bundled/{name}/{VENDOR_DIR}/{fname}")

    return {
        "kind": "bundle",
        "mcp_bundled": name,
        "vendored": vendored,
        "generated": generated,
    }


def build(registries: RegistryArray, name: str, image: str | None = None) -> dict:
    """docker イメージビルドコマンドを生成して返す（実行はしない）。

    タグの決め方:
    - `-t`（引数 image）があればそれをフルタグとして使う。
    - 無ければ bundle.yml の `image`（名前のみ）に **ローカルビルド前提でまず `:latest`** を付ける。
      宣言の `version` はタグにはまだ使わない（バージョン更新コマンドは後日）。
    """
    spec = _spec(registries, name)
    version = spec.get("version", "0.0.1")
    tag = image or f"{spec.get('image') or f'juice/{name}'}:latest"
    context = registries.location("mcp_bundled", name, VENDOR_DIR)
    return {
        "kind": "build",
        "mcp_bundled": name,
        "image": tag,
        "version": version,
        "context": context,
        "command": f"docker build -t {tag} {context}",
    }


def _image_tag(registries: RegistryArray, name: str, image: str | None) -> str:
    spec = _spec(registries, name)
    return image or f"{spec.get('image') or f'juice/{name}'}:latest"


def run(registries: RegistryArray, name: str, image: str | None = None) -> dict:
    """docker run コマンド（mcp_server を stdio で起動）を生成して返す。

    bundle はそれ自体が stdio(JSON-RPC) の mcp_server なので、`-i` で対話接続する。
    応答例: echo '<JSON-RPC request>' | docker run --rm -i <image>
    """
    tag = _image_tag(registries, name, image)
    return {
        "kind": "run",
        "mcp_bundled": name,
        "image": tag,
        "command": f"docker run --rm -i {tag}",
    }
