"""mcp_bundled のバンドル。

`bundle.yml` が mcp_bundled の **定義 + ビルド宣言**（instance の index.yml に相当する単一の
ソースファイル）。`llm` ブロックで会話に使う LLM を宣言する（API キーは環境変数 or ファイルで
注入し、値は書かない）。

会話は **LangGraph** で構成する: bundled tool（MCP server）を `langchain-mcp-adapters` で取り込み、
`langchain-anthropic` の Claude と `create_react_agent` で結ぶ。生成物（vendor/）は `langgraph dev`
（Studio UI）/ FastAPI（会話 API）/ MCP server のいずれでも起動できる。

段階:
- `init`:   `bundle.yml` の雛形を生成。`--clean` は定義を残して一掃。
- `bundle`: 内包物を vendoring し、LangGraph 一式（graph.py / api.py / mock_server.py /
            entrypoint.py / langgraph.json / agent.json / requirements.txt / Dockerfile）を生成。
- `build`:  docker でイメージをビルド。
- `run`:    mode（api / ui / mcp_server）に応じてサービスを docker 起動。
"""

from __future__ import annotations

import json

import yaml

from .config import ENTRY_FILES, LAYERS
from .registry import RegistryArray

SPEC_FILE = "bundle.yml"
VENDOR_DIR = "vendor"
DEFAULT_INCLUDE = ["subagent", "skills", "tools"]
DEFAULT_LLM = {
    "provider": "anthropic",
    "model": "claude-opus-4-8",
    "api_key_env": "ANTHROPIC_API_KEY",
    "api_key_file": None,
}
DEFAULT_PORT = 8000
RUN_MODES = ("api", "ui", "mcp_server")

# --- 生成テンプレート ----------------------------------------------------------

BUNDLE_YML_TEMPLATE = """\
# bundle.yml — mcp_bundled の定義 + ビルド宣言（juice mcp_bundled init が生成。編集可）
apiVersion: juice/v1
kind: mcp_bundled
name: {name}
namespace: {namespace}

# build で生成する docker イメージ名（タグなし）と version
image: juice/{name}
version: 0.0.1

# 会話に使う LLM。API キーは環境変数 or ファイルで注入（値は書かない）
llm:
  provider: anthropic
  model: claude-opus-4-8
  api_key_env: ANTHROPIC_API_KEY
  # api_key_file: /run/secrets/anthropic_api_key

# 結線（定義）— 編集して埋める
subagent:
skills: []
tools: {{}}

# vendoring 対象（省略時は subagent/skills/tools）
include:
  - subagent
  - skills
  - tools
"""

REQUIREMENTS_TXT = """\
# generated by juice — LangGraph で MCP server と Claude を連携する
# inmem 開発サーバ（langgraph dev / Studio）系は dev 版が混ざると不整合になるため
# 整合する安定版にピン留めする（pip が pre-release を引かないように）。
langgraph
langgraph-cli[inmem]==0.4.29
langgraph-api==0.10.0
langgraph-runtime-inmem==0.30.0
langgraph-sdk==0.4.2
langchain-anthropic
langchain-mcp-adapters
mcp
fastapi
uvicorn
"""

DOCKERFILE = """\
# generated by juice — `juice mcp_bundled bundle` で再生成（手編集しない）
FROM python:3.12-slim
WORKDIR /app
# 依存だけ先に入れてレイヤをキャッシュ（requirements.txt 不変なら再インストールしない）
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
# その後に成果物本体をコピー（ソース変更はこのレイヤ以降だけを無効化）
COPY . /app
EXPOSE 8000
# mode は docker run の引数で渡す（api / ui / mcp_server）。既定は api。
ENTRYPOINT ["python", "entrypoint.py"]
CMD ["api"]
"""

LANGGRAPH_JSON = """\
{
  "dependencies": ["."],
  "graphs": { "agent": "./graph.py:make_graph" },
  "http": { "app": "./api.py:app" },
  "env": "./.env",
  "python_version": "3.12"
}
"""

ENV_FILE = "# API キーは docker run -e で注入する（ここには書かない）\n"

GRAPH_PY = '''\
"""LangGraph グラフ（自動生成）。

bundled MCP server を langchain-mcp-adapters で取り込み、Claude（langchain-anthropic）と
create_react_agent で結ぶ。langgraph.json はこの make_graph を参照する（Studio / dev / API 共通）。
"""

from __future__ import annotations

import json
import os
import pathlib

from langchain_anthropic import ChatAnthropic
from langchain_mcp_adapters.client import MultiServerMCPClient
from langgraph.prebuilt import create_react_agent

HERE = pathlib.Path(__file__).parent
CONFIG = json.loads((HERE / "agent.json").read_text(encoding="utf-8"))


def resolve_api_key() -> str | None:
    """api_key_file / api_key_env から API キーを解決して返す（無ければ None）。"""
    path = CONFIG.get("api_key_file")
    if path and os.path.exists(path):
        return pathlib.Path(path).read_text(encoding="utf-8").strip()
    env = CONFIG.get("api_key_env") or "ANTHROPIC_API_KEY"
    return os.environ.get(env)


def _ensure_api_key() -> None:
    """解決したキーを ANTHROPIC_API_KEY に設定する（ChatAnthropic が読む）。"""
    key = resolve_api_key()
    if key:
        os.environ["ANTHROPIC_API_KEY"] = key


def _connections() -> dict:
    conns = {}
    for name, c in CONFIG.get("mcp_servers", {}).items():
        args = [str(HERE / a) if isinstance(a, str) and a.endswith(".py") else a for a in c.get("args", [])]
        conns[name] = {"transport": c.get("transport", "stdio"), "command": c["command"], "args": args}
    return conns


async def make_graph():
    """MCP tool を取り込んだ ReAct エージェントグラフを返す（langgraph.json のエントリ）。"""
    _ensure_api_key()
    client = MultiServerMCPClient(_connections())
    tools = await client.get_tools()
    model = ChatAnthropic(model=CONFIG["model"])
    return create_react_agent(model, tools, prompt=CONFIG.get("system") or None)
'''

API_PY = '''\
"""会話 API（OpenAI 互換）＋ 簡易チャット UI（自動生成）。

- POST /v1/chat/completions : LangGraph グラフに会話を渡して応答（OpenAI 互換）。
- GET  /chat                : ローカル完結の簡易チャット画面（/v1/chat/completions を叩く）。
  ※ `/ui` は langgraph dev（Studio）が使うため避け、`/chat` に置いて衝突を回避。
- GET  /                    : /chat へリダイレクト。
"""

from __future__ import annotations

import time

from fastapi import FastAPI
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse

from graph import CONFIG, make_graph, resolve_api_key

app = FastAPI()
_agent = None


async def _get_agent():
    global _agent
    if _agent is None:
        _agent = await make_graph()
    return _agent


CHAT_HTML = """
<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><title>__NAME__ — chat</title>
<style>
 body{font-family:system-ui,sans-serif;max-width:720px;margin:2rem auto;padding:0 1rem}
 #log{border:1px solid #ddd;border-radius:8px;padding:1rem;height:60vh;overflow:auto;background:#fafafa}
 .msg{margin:.6rem 0;white-space:pre-wrap}
 .u{color:#0a7}.a{color:#222}
 form{display:flex;gap:.5rem;margin-top:.6rem}
 input{flex:1;padding:.6rem;border:1px solid #ccc;border-radius:6px}
 button{padding:.6rem 1rem;border:0;border-radius:6px;background:#0a7;color:#fff;cursor:pointer}
</style></head><body>
<h2>__NAME__</h2>
<div id="log"></div>
<form id="f"><input id="t" placeholder="メッセージを入力…" autocomplete="off" autofocus><button>送信</button></form>
<script>
const log=document.getElementById("log"),f=document.getElementById("f"),t=document.getElementById("t");
const messages=[];
function add(role,text){const d=document.createElement("div");d.className="msg "+(role==="user"?"u":"a");d.textContent=(role==="user"?"あなた: ":"AI: ")+text;log.appendChild(d);log.scrollTop=log.scrollHeight;return d;}
f.onsubmit=async(e)=>{e.preventDefault();const text=t.value.trim();if(!text)return;t.value="";
 add("user",text);messages.push({role:"user",content:text});
 const ph=add("assistant","…");
 try{
  const r=await fetch("/v1/chat/completions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messages})});
  const raw=await r.text();
  let data=null; try{data=JSON.parse(raw);}catch(_){}
  if(!r.ok){
   const msg=(data&&data.error&&data.error.message)||raw||("HTTP "+r.status);
   ph.textContent="⚠️ エラー: "+msg; messages.pop(); return;
  }
  const reply=(((data&&data.choices||[])[0]||{}).message||{}).content;
  if(reply==null){ph.textContent="⚠️ エラー: 想定外の応答 "+raw; messages.pop(); return;}
  ph.textContent="AI: "+reply;messages.push({role:"assistant",content:reply});
 }catch(err){ph.textContent="⚠️ エラー: "+err; messages.pop();}
};
</script></body></html>
"""


@app.get("/")
def root():
    return RedirectResponse("/chat")


@app.get("/chat", response_class=HTMLResponse)
@app.get("/chat/", response_class=HTMLResponse, include_in_schema=False)
def chat_ui():
    return CHAT_HTML.replace("__NAME__", CONFIG.get("name", "chat"))


@app.post("/v1/chat/completions")
async def chat_completions(body: dict):
    # 原因を分かりやすく返す: キー未設定は 400、それ以外の失敗は 502（どちらも JSON）。
    if not resolve_api_key():
        env = CONFIG.get("api_key_env") or "ANTHROPIC_API_KEY"
        return JSONResponse(
            status_code=400,
            content={"error": {
                "type": "missing_api_key",
                "message": f"API キーが未設定です。環境変数 {env}（または api_key_file）を設定して起動してください。",
            }},
        )
    messages = [
        {"role": m["role"], "content": m["content"]}
        for m in body.get("messages", [])
        if m.get("role") in ("system", "user", "assistant")
    ]
    try:
        agent = await _get_agent()
        result = await agent.ainvoke({"messages": messages})
        text = result["messages"][-1].content
        if isinstance(text, list):  # content blocks の場合は text を連結
            text = "".join(b.get("text", "") for b in text if isinstance(b, dict))
    except Exception as e:  # noqa: BLE001  LLM/接続エラー等を JSON で返す
        return JSONResponse(
            status_code=502,
            content={"error": {"type": type(e).__name__, "message": str(e)}},
        )
    return {
        "id": f"chatcmpl-{int(time.time() * 1000)}",
        "object": "chat.completion",
        "model": CONFIG["model"],
        "choices": [{"index": 0, "message": {"role": "assistant", "content": text}, "finish_reason": "stop"}],
    }
'''

ENTRYPOINT_PY = '''\
"""エントリポイント（自動生成）。mode に応じてサービスを起動する。

    api         … 会話 API（FastAPI / uvicorn, OpenAI 互換）
    ui          … LangGraph Studio（langgraph dev）
    mcp_server  … バック MCP server（stdio）

mode は docker run の引数（CMD）または環境変数 MODE で渡す。既定は api。
"""

from __future__ import annotations

import os
import sys

MODE = (sys.argv[1] if len(sys.argv) > 1 else os.environ.get("MODE", "api")).strip()
PORT = os.environ.get("PORT", "8000")


def main() -> int:
    if MODE == "api":
        os.execvp("uvicorn", ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", PORT])
    if MODE == "ui":
        os.execvp("langgraph", ["langgraph", "dev", "--host", "0.0.0.0", "--port", PORT, "--no-browser"])
    if MODE == "mcp_server":
        import json
        import pathlib

        here = pathlib.Path(__file__).parent
        servers = (json.loads((here / "agent.json").read_text(encoding="utf-8")).get("mcp_servers") or {})
        if not servers:
            print("no mcp_servers in agent.json", file=sys.stderr)
            return 2
        srv = next(iter(servers.values()))  # 先頭 tool の server を起動
        args = [str(here / a) if isinstance(a, str) and a.endswith(".py") else a for a in srv.get("args", [])]
        os.execvp(srv["command"], [srv["command"], *args])
    print(f"unknown mode: {MODE} (use api / ui / mcp_server)", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
'''

# --- 内部ヘルパ ----------------------------------------------------------------


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """`---` で囲った YAML frontmatter と本文に分割する。fence が無ければ全体を本文扱い。"""
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) == 3:
            return yaml.safe_load(parts[1]) or {}, parts[2].lstrip("\n")
    return {}, text


def _spec(registries: RegistryArray, name: str) -> dict:
    return yaml.safe_load(registries.read("mcp_bundled", name, SPEC_FILE)) or {}


def _deps(spec: dict, include: list[str]) -> list[tuple[str, str]]:
    deps: list[tuple[str, str]] = []
    if "subagent" in include and spec.get("subagent"):
        deps.append(("subagent", spec["subagent"]))
    if "skills" in include and spec.get("skills"):
        deps += [("skill", s) for s in spec["skills"]]
    if "tools" in include and spec.get("tools"):
        tools = spec["tools"]
        names = list(tools.keys()) if isinstance(tools, dict) else list(tools)
        deps += [("tool", t) for t in names]
    return deps


def _agent_config(registries: RegistryArray, name: str, spec: dict) -> dict:
    """graph.py が読む解決済み設定（model / system / api key / MCP server）を組み立てる。"""
    llm = {**DEFAULT_LLM, **(spec.get("llm") or {})}
    system = ""
    model = llm.get("model")
    subagent = spec.get("subagent")
    if subagent:
        meta, body = parse_frontmatter(registries.read("subagent", subagent))
        system = body.strip()
        if not (spec.get("llm") or {}).get("model"):
            model = meta.get("model") or model
    # 各 tool パッケージ（tools/<name>/index.md）から MCP server 起動定義を構築。
    # args の .py は vendor/tools/<name>/ 配下へ prefix（その server が起動される）。
    mcp_servers: dict = {}
    tools = spec.get("tools") or {}
    for tname in (list(tools.keys()) if isinstance(tools, dict) else list(tools)):
        tmeta, _ = parse_frontmatter(registries.read("tool", tname))
        raw_args = tmeta.get("args") or []
        args = [
            f"{LAYERS['tool']}/{tname}/{a}" if isinstance(a, str) and a.endswith(".py") else a
            for a in raw_args
        ]
        mcp_servers[tname] = {
            "command": tmeta.get("command", "python"),
            "args": args,
            "transport": "stdio",
        }
    return {
        "name": name,
        "provider": llm.get("provider", "anthropic"),
        "model": model,
        "api_key_env": llm.get("api_key_env"),
        "api_key_file": llm.get("api_key_file"),
        "system": system,
        "mcp_servers": mcp_servers,
    }


def _vendor(registries: RegistryArray, name: str) -> list[str]:
    """内包物を **パッケージ丸ごと**（index.md だけでなく server.py 等も）vendoring する。"""
    spec = _spec(registries, name)
    include = spec.get("include") or DEFAULT_INCLUDE
    registries.remove("mcp_bundled", name, VENDOR_DIR)
    vendored: list[str] = []
    for layer, dep in _deps(spec, include):
        for rel in registries.list_files(layer, dep):  # パッケージ配下の全ファイル
            raw = registries.read(layer, dep, rel)
            out = f"{VENDOR_DIR}/{LAYERS[layer]}/{dep}/{rel}"
            registries.write("mcp_bundled", name, out, raw)
            vendored.append(f"mcp_bundled/{name}/{out}")
    return vendored


# --- コマンド ------------------------------------------------------------------


def init(registries: RegistryArray, name: str, clean: bool = False) -> dict:
    """`bundle.yml` の雛形を生成して初期化する（既存なら要 clean）。"""
    exists = registries.exists("mcp_bundled", name, SPEC_FILE)
    if not clean and exists:
        raise FileExistsError(
            f"already initialized: mcp_bundled/{name}/{SPEC_FILE} (use --clean to clean & reinitialize)"
        )
    if clean:
        spec_text = registries.read("mcp_bundled", name, SPEC_FILE) if exists else None
        registries.remove("mcp_bundled", name, "")
        if spec_text is None:
            spec_text = BUNDLE_YML_TEMPLATE.format(namespace=registries.namespace, name=name)
        registries.write("mcp_bundled", name, SPEC_FILE, spec_text)
    else:
        registries.write(
            "mcp_bundled", name, SPEC_FILE,
            BUNDLE_YML_TEMPLATE.format(namespace=registries.namespace, name=name),
        )
    return {"kind": "init", "mcp_bundled": name, "spec": f"mcp_bundled/{name}/{SPEC_FILE}"}


def bundle(registries: RegistryArray, name: str) -> dict:
    """内包物を vendoring し、LangGraph の build コンテキスト一式を生成する。"""
    vendored = _vendor(registries, name)
    spec = _spec(registries, name)
    agent_json = json.dumps(_agent_config(registries, name, spec), ensure_ascii=False, indent=2)

    generated = []
    for fname, text in (
        ("requirements.txt", REQUIREMENTS_TXT),
        ("graph.py", GRAPH_PY),
        ("api.py", API_PY),
        ("entrypoint.py", ENTRYPOINT_PY),
        ("langgraph.json", LANGGRAPH_JSON),
        (".env", ENV_FILE),
        ("agent.json", agent_json),
        ("Dockerfile", DOCKERFILE),
    ):
        registries.write("mcp_bundled", name, f"{VENDOR_DIR}/{fname}", text)
        generated.append(f"mcp_bundled/{name}/{VENDOR_DIR}/{fname}")

    return {"kind": "bundle", "mcp_bundled": name, "vendored": vendored, "generated": generated}


def build(registries: RegistryArray, name: str, image: str | None = None) -> dict:
    """docker イメージビルドコマンドを生成して返す。"""
    spec = _spec(registries, name)
    version = spec.get("version", "0.0.1")
    tag = image or f"{spec.get('image') or f'juice/{name}'}:latest"
    context = registries.location("mcp_bundled", name, VENDOR_DIR)
    return {
        "kind": "build",
        "mcp_bundled": name,
        "image": tag,
        "version": version,
        "context": context,
        "command": f"docker build -t {tag} {context}",
    }


def run(
    registries: RegistryArray,
    name: str,
    mode: str = "api",
    image: str | None = None,
    env_file: str | None = None,
) -> dict:
    """mode（api / ui / mcp_server）に応じた docker run コマンドを生成して返す。

    env_file を指定すると docker の `--env-file` で .env を読み込む（host 環境変数の
    `-e <api_key_env>` 透過も併用。後勝ちで .env が優先）。
    """
    if mode not in RUN_MODES:
        raise ValueError(f"unknown mode: {mode} (use {' / '.join(RUN_MODES)})")
    spec = _spec(registries, name)
    llm = {**DEFAULT_LLM, **(spec.get("llm") or {})}
    tag = image or f"{spec.get('image') or f'juice/{name}'}:latest"
    port = spec.get("port", DEFAULT_PORT)
    key_env = llm.get("api_key_env") or "ANTHROPIC_API_KEY"
    envfile = f"--env-file {env_file} " if env_file else ""
    if mode == "mcp_server":
        command = f"docker run --rm -i -e {key_env} {envfile}{tag} mcp_server"
    else:
        command = f"docker run --rm -p {port}:{port} -e {key_env} {envfile}{tag} {mode}"
    return {"kind": "run", "mcp_bundled": name, "mode": mode, "image": tag, "port": port, "command": command}
